<?php

namespace app\modules\admin_strategy\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "case".
 *
 * @property int $id
 * @property int $product_id
 * @property string $preview
 * @property string $title_ua
 * @property string $s_desc_ua
 * @property string|null $title_ru
 * @property string|null $s_desc_ru
 * @property string|null $title_en
 * @property string|null $s_desc_en
 * @property int $active
 * @property string $url
 */
class Cases extends \yii\db\ActiveRecord
{
    public $file_preview;
    public static function tableName()
    {
        return 'case';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['product_id', 'preview', 'title_ua', 's_desc_ua', 'url', 'text_ua'], 'required'],
            [['product_id', 'active'], 'integer'],
            [['preview', 'url'], 'string', 'max' => 255],
            [['title_ua', 'title_ru', 'title_en'], 'string', 'max' => 60],
            [['s_desc_ua', 's_desc_ru', 's_desc_en'], 'string', 'max' => 150],
            [['text_ua', 'text_ru', 'text_en'], 'string'],
            //[['file_preview'], 'image']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'preview' => 'Preview',
            'title_ua' => 'Title Ua',
            's_desc_ua' => 'S Desc Ua',
            'title_ru' => 'Title Ru',
            's_desc_ru' => 'S Desc Ru',
            'title_en' => 'Title En',
            's_desc_en' => 'S Desc En',
            'active' => 'Active',
            'url' => 'Url',
        ];
    }

    public function beforeSave($insert)
    {
        if ($file = UploadedFile::getInstance($this, 'file_preview')){
            $extension = $file->extension;
            $path_to_dir = Yii::getAlias('@webroot/').'uploads/case/';
            $path_file = '';
            $file_name = '';

            do {
                $file_name = uniqid();
                $path_file = $path_to_dir . $file_name . "." . $extension;
            } while (file_exists($path_file));

            $this->preview =  $file_name;
            $file->saveAs($path_file);
            imagewebp(imagecreatefromjpeg($path_file), $path_to_dir . $file_name . '.webp', 90);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
